name: cinespot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  json_serializable: ^6.9.3
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_rating: ^2.0.2
  url_launcher: ^6.3.1
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.5.2
  share: ^2.0.4
  visibility_detector: ^0.4.0+2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/
